import Head from 'next/head'
import { ApolloClient, InMemoryCache, gql } from "@apollo/client"

import HomePage from '../components/HomePage'
import Footer from '../components/Footer'

export default function Home({ allCategories }) {
  return (
    <>
      <Head>
        <title>Time Stone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-gradient-to-b from-chineseblack via-chineseblack2 to-darkcharcoal'>
        <HomePage categories={allCategories} />
        <Footer />
      </main>
    </>
  )
}

export async function getStaticProps() {

  const client = new ApolloClient({
    uri: process.env.CONTENT_API,
    cache: new InMemoryCache(),
  })

  const data = await client.query({
    query: gql`
          query Query {
              categories {
                  id
                  slug
                  name
                  image {
                    url
                  }
              }
          }
      `
  })

  const allCategories = data.data.categories

  return {
    props: {
      allCategories
    }
  }
}
