import Head from 'next/head'

import HomePage from '../components/HomePage'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Time Stone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-gradient-to-b from-chineseblack via-chineseblack2 to-darkcharcoal'>
        <HomePage />
        <Footer />
      </main>
    </>
  )
}
